### ISSUE TITLE
Fisher Callhome

### ISSUE THREAD

**Issue by esalesky** [kahne/SpeechTransProgress#1]
This is a great resource, thank you very much for creating it!

In the data table, Fisher should be 160hr Es->En. Callhome is an additional 20hr Es->En, I would recommend keeping separate due to differences in the corpora (chiefly number of references) and their use in previous papers. 
The 38hr En->Es is a mistake in the MuST-C paper table, in part from misreading the original corpus paper’s abstract (there is 4-way parallel data released for the 38hr of dev/dev2/eval sets).

**Comment by kahne** [comment]
Hi @esalesky ,

Thanks for pointing this out! I will fix the typo.

The 160hr/20hr number is for the full Fisher/Callhome ASR corpus. But I think the MuST-C paper and my list tries to focus on speech translation and 38hr is the number for translated data in Fisher & Callhome.

**Comment by esalesky** [comment]
Hi @kahne, the full 160hr/20hr corpora were actually translated and released with the IWSLT 2013 paper -- the subsequent speech translation publications using this corpus use all 160hr of Fisher parallel speech + translations for end-to-end training and evaluation. 

Thank you for fixing this! If possible, it would be nice to fix in the CoVoST paper as well, since there is still a week before camera-ready.

**Comment by kahne** [comment]
Thanks for the clarification! Updated.
